ai_apps/urls.py
from django.conf.urls.static import static
from django.urls import path
from ai_apps import views
from ai_apps.views import translator, index, email, customer_service_assistant, chatbot, auth
from django.conf import settings

urlpatterns = [
                  # 登陆注册相关
                  path("auth/register/manual", auth.register_manual, name="register_manual"),
                  path('auth/', auth.login_page, name='login_page'),
                  path('auth/login/', auth.login_view, name='login'),

                  path("", index.index, name="index"),
                  # 翻译助手相关
                  path("trans/", translator.translator, name="translator"),
                  path("trans/translate/", translator.pack_trans_stream, name="pack_trans_stream"),
                  # 邮件助手相关
                  path("email/", email.email_writer, name="email_writer"),
                  path("email/generate/", email.pack_email_stream, name="pack_email_stream"),
                  # 客服助手相关
                  path("csa/", customer_service_assistant.customer_service_assistant, name="csa"),
                  path("csa/generate/", customer_service_assistant.pack_reply_stream, name="pack_reply_stream"),
                  # 聊天机器人相关
                  path("chatbot/", chatbot.chatbot, name="chatbot"),
                  path("chatbot/generate/", chatbot.pack_chatbot_stream, name="pack_chatbot_stream"),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from my_application import views
# path 必须是相对路径，否则会报错
urlpatterns = [
    path("admin/", admin.site.urls),
    path("ai_apps/", include("ai_apps.urls")),
    path("pknight_docs/", include("pknight_docs.urls")),
    path("pknight/", views.pknight, name="pknight"),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ai_apps/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    """ 用户 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)

    class Meta:
        verbose_name = "用户表"
        db_table = "users"

ai_apps/forms.py
from django import forms
from django.core.validators import RegexValidator

from ai_apps.utils.encrypt import md5


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username",
        label_suffix="",  # 去掉label后面的冒号
        required=True,  # 校验不能为空
        # 添加正则表达式，要求含有英文字母和数字，且长度为6-12位
        widget=forms.TextInput(attrs={
            "class": "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline",
            "placeholder": "用户名"}),
    )
    password = forms.CharField(
        label="Password",
        label_suffix="",  # 去掉label后面的冒号
        required=True,  # 校验不能为空
        # 添加正则表达式，要求含有英文字母,英文标点符号或者下划线和数字，且长度为6-12位
        widget=forms.PasswordInput(attrs={
            "class": "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline",
            "placeholder": "密码"}, render_value=True),
    )  # render_value=True,即使我们输错密码，先前输入的密码仍然会显示在输入框中

    def clean_username(self):
        return self.cleaned_data.get('username')

    def clean_password(self):
        # 预先对密码进行加密，视图函数中的加密就可以省略了，这样就可以保证密码的一致性
        # 直接返回加密后的密码
        password_hash = md5(self.cleaned_data.get('password'))
        print(password_hash)
        # 确保返回一个字符串
        return str(password_hash)


class TranslationForm(forms.Form):
    # 用来接收用户输入的文本
    text = forms.CharField(label='原文',
                           # max_length=1000,
                           widget=forms.Textarea(attrs={'class': 'cus-textarea'}))

    # 用来接收用户选择的语言
    language = forms.ChoiceField(label='翻译成',
                                 required=True,
                                 choices=[('zh', '中文'), ('en', '英文'), ('ru', '俄文'), ('ko', '韩文')],
                                 widget=forms.Select(attrs={'class': 'select select-bordered w-32'}))

    # 用来接收翻译好的文本
    translation = forms.CharField(label='译文',
                                  widget=forms.Textarea(attrs={'class': 'cus-textarea'}))



class EmailWriterForm(forms.Form):
    # 用来接收用户输入的文本
    received_email = forms.CharField(label='我收到的邮件',
                           widget=forms.Textarea(attrs={'class': 'cus-textarea'}))

    #language = forms.ChoiceField(label='翻译成',
                                 # required=True,
                                 # choices=[('zh', '中文'), ('en', '英文'), ('ru', '俄文'), ('ko', '韩文')],
                                 # widget=forms.Select(attrs={'class': 'select select-bordered w-32'}))
    # 我对于ai助手帮我写的邮件的额外要求
    my_extra_requirement = forms.CharField(label='我对于ai助手帮我写的邮件的额外要求',
                                    initial="be polite",
                                    widget=forms.TextInput(attrs={'class': 'p-2.5 w-full text-xl text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500'}))
    include_info = forms.CharField(label='我想在回复中包含的信息',
                                    initial="",
                                    widget=forms.Textarea(attrs={'class': 'p-2.5 w-full h-20 text-xl text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500'}))
    # 用来接收翻译好的文本
    my_response_email = forms.CharField(label='我的回复',
                                  widget=forms.Textarea(attrs={'class': 'cus-textarea'}))


class CustomerServiceAssistantForm(forms.Form):
    # 用来接收用户输入的文本
    customer_message = forms.CharField(label='顾客的信息',
                           widget=forms.Textarea(attrs={'class': 'cus-textarea'}))

    #language = forms.ChoiceField(label='翻译成',
                                 # required=True,
                                 # choices=[('zh', '中文'), ('en', '英文'), ('ru', '俄文'), ('ko', '韩文')],
                                 # widget=forms.Select(attrs={'class': 'select select-bordered w-32'}))
    # 我对于ai助手帮我写的邮件的额外要求
    my_extra_requirement = forms.CharField(label='我回复时要注意的事项',
                                    initial="be polite",
                                    widget=forms.TextInput(attrs={'class': 'p-2.5 w-full text-xl text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500'}))
    include_info = forms.CharField(label='我想在回复中包含的信息',
                                    initial="",
                                    widget=forms.Textarea(attrs={'class': 'p-2.5 w-full h-20 text-xl text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500'}))
    # 用来接收翻译好的文本
    my_reply = forms.CharField(label='我的回复',
                                  widget=forms.Textarea(attrs={'class': 'cus-textarea'}))

ai_apps/views/chatbot.py
import json
from django.conf import settings
from ai_apps import forms
from utils.base import BaseResponse
from django.shortcuts import render
import openai
from django.http import JsonResponse, StreamingHttpResponse, HttpResponse

def chatbot(request):
    # 只是为了页面展示

    return render(request, "chatbot.html")


# def translate(request):
#
#     res = BaseResponse()
#     # print(request.POST)
#
#     text = request.POST.get('text')
#     # print(type(text))
#     # template里面的变量要注意空格
#     try:
#         template = """
#         translate English to Chinese:
#         English: {original_text}
#         Chinese:
#         """
#         prompt = PromptTemplate(template=template, input_variables=["original_text"])
#         llm = OpenAI(streaming=True,verbose=True, temperature=0)# 不写参数就是默认的，默认model_name = "text-davinci-003"
#         llm_chain = LLMChain(prompt=prompt, llm=llm,callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))
#         original_text = text
#         result = llm_chain.run(original_text)
#         res.status = True
#         # res.date的值是一个字典，添加一个键值对，key是translation，value是result
#         res.data = {}
#         res.data["translation"] = result
#         print(result)
#     except Exception as e:
#         print(e)
#
#     return JsonResponse(res.dict, json_dumps_params={'ensure_ascii': False})

# 原生openai,使用completion，贵，不推荐

# def translate(request):
#
#     res = BaseResponse()
#     # print(request.POST)
#
#     text = request.POST.get('text')
#     # print(type(text))
#     # template里面的变量要注意空格
#     try:
#         template = """
#         translate English to Chinese:
#         English: {original_text}
#         Chinese:
#         """
#         prompt=template.format(original_text=text)
#         completion = openai.Completion.create(model="text-davinci-003", prompt=prompt, temperature=0)
#         result = completion.choices[0].text
#         res.status = True
#         # res.date的值是一个字典，添加一个键值对，key是translation，value是result
#         res.data = {}
#         res.data["translation"] = result
#         #print(completion)
#         #print(result)
#     except Exception as e:
#         print(e)
#
#     return JsonResponse(res.dict, json_dumps_params={'ensure_ascii': False})

# 原生openai,使用chatcompletion，便宜，推荐


def pack_chatbot_stream(request):
    # 当请求头stop为true时，停止推送数据
    stop = request.GET.get('stop')

    if stop == 'false':
        userInputText = request.GET.get('userInputText')
        print(userInputText)
        stream_data = generate_stream_data(userInputText)
        response = StreamingHttpResponse(stream_data, status=200, content_type='text/event-stream')
        # 针对浏览器端--浏览器不应该缓存响应内容。这样可以确保每次请求都会从服务器获取最新的数据，而不是使用本地缓存。
        response['Cache-Control'] = 'no-cache'
        # 针对nginx服务器端--服务器端不缓存数据，nginx就不会缓存数据，这样就可以实时看到数据了
        response['X-Accel-Buffering'] = 'no'
        return response
    return HttpResponse('后台已经停止推送数据')
def generate_stream_data(userInputText):
    chunks = openai.ChatCompletion.create(
        model=settings.MODELTYPES.get("gpt3.5turbo"),
        messages=[{"role": "system",
                   "content": "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown."},
                  {"role": "user", "content": userInputText}
                  ],
        temperature=0,
        stream=True,
    )
    for chunk in chunks:

        result = chunk.choices[0].get("delta", {}).get("content")
        finish_reason = chunk.choices[0].get("finish_reason")
        if not result:
            continue
        if result is not None:
            json_str = {"content": result}
            bytes_str = json.dumps(json_str, ensure_ascii=False)
            yield f"data: {bytes_str}\n\n".encode('utf-8')
        if finish_reason == "stop":
            break
    yield 'data: \n\n'

ai_apps/views/customer_service_assistant.py
import json
from django.conf import settings
from ai_apps import forms
from utils.base import BaseResponse
from django.shortcuts import render
import openai
from django.http import JsonResponse, StreamingHttpResponse, HttpResponse


def customer_service_assistant(request):
    # 只是为了页面展示
    CustomerServiceAssistantForm = forms.CustomerServiceAssistantForm()

    return render(request, "customer_service_assistant.html",
                  {"CustomerServiceAssistantForm": CustomerServiceAssistantForm})


# def translate(request):
#
#     res = BaseResponse()
#     # print(request.POST)
#
#     text = request.POST.get('text')
#     # print(type(text))
#     # template里面的变量要注意空格
#     try:
#         template = """
#         translate English to Chinese:
#         English: {original_text}
#         Chinese:
#         """
#         prompt = PromptTemplate(template=template, input_variables=["original_text"])
#         llm = OpenAI(streaming=True,verbose=True, temperature=0)# 不写参数就是默认的，默认model_name = "text-davinci-003"
#         llm_chain = LLMChain(prompt=prompt, llm=llm,callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))
#         original_text = text
#         result = llm_chain.run(original_text)
#         res.status = True
#         # res.date的值是一个字典，添加一个键值对，key是translation，value是result
#         res.data = {}
#         res.data["translation"] = result
#         print(result)
#     except Exception as e:
#         print(e)
#
#     return JsonResponse(res.dict, json_dumps_params={'ensure_ascii': False})

# 原生openai,使用completion，贵，不推荐

# def translate(request):
#
#     res = BaseResponse()
#     # print(request.POST)
#
#     text = request.POST.get('text')
#     # print(type(text))
#     # template里面的变量要注意空格
#     try:
#         template = """
#         translate English to Chinese:
#         English: {original_text}
#         Chinese:
#         """
#         prompt=template.format(original_text=text)
#         completion = openai.Completion.create(model="text-davinci-003", prompt=prompt, temperature=0)
#         result = completion.choices[0].text
#         res.status = True
#         # res.date的值是一个字典，添加一个键值对，key是translation，value是result
#         res.data = {}
#         res.data["translation"] = result
#         #print(completion)
#         #print(result)
#     except Exception as e:
#         print(e)
#
#     return JsonResponse(res.dict, json_dumps_params={'ensure_ascii': False})

# 原生openai,使用chatcompletion，便宜，推荐


def pack_reply_stream(request):
    # 当请求头stop为true时，停止推送数据
    stop = request.GET.get('stop')

    if stop == 'false':
        received_email = request.GET.get('customer_message')
        include_info = request.GET.get('include_info')
        my_extra_requirement = request.GET.get('my_extra_requirement')
        stream_data = generate_stream_data(received_email, include_info, my_extra_requirement)
        response = StreamingHttpResponse(stream_data, status=200, content_type='text/event-stream')
        # 针对浏览器端--浏览器不应该缓存响应内容。这样可以确保每次请求都会从服务器获取最新的数据，而不是使用本地缓存。
        response['Cache-Control'] = 'no-cache'
        # 针对nginx服务器端--服务器端不缓存数据，nginx就不会缓存数据，这样就可以实时看到数据了
        response['X-Accel-Buffering'] = 'no'
        return response
    return HttpResponse('后台已经停止推送数据')


def generate_stream_data(customer_message, include_info, my_extra_requirement):
    template = """
                We received a message from a customer ：{customer_message},
                ##
                help me write a reply in English that includes this information: {include_info}? 
                ##
                make sure the replay in a casual chat format without a letter structure. Feel free to use emojis if necessary.
                ##
                Additionally, when giving the reply, follow these conditions: {my_extra_requirement}.
                """
    prompt = template.format(
        customer_message=customer_message,
        include_info=include_info,
        my_extra_requirement=my_extra_requirement
    )
    chunks = openai.ChatCompletion.create(
        model=settings.MODELTYPES.get("gpt4"),
        messages=[{"role": "system",
                   "content": "You are a reliable AI live chat customer service assistant who can help you write satisfying English messages based on your prompts."},
                  {"role": "user", "content": prompt}
                  ],
        temperature=0,
        stream=True,
    )
    for chunk in chunks:

        result = chunk.choices[0].get("delta", {}).get("content")
        finish_reason = chunk.choices[0].get("finish_reason")
        if result is None:
            continue
        if result is not None:
            json_str = {"content": result}
            bytes_str = json.dumps(json_str, ensure_ascii=False)
            yield f"data: {bytes_str}\n\n".encode('utf-8')
        if finish_reason == "stop":
            break
    yield 'data: \n\n'

ai_apps/views/index.py
from django.shortcuts import render
def index(request):
    return render(request, "index_for_ai_apps.html")

ai_apps/templates/ai_apps_login.html
{% extends 'base_for_ai_apps.html' %}
{% load static %}

{% block title %}
	登陆
{% endblock title %}

{% block content %}
	<form class="m-8" method="post" action={% url 'login' %}>
		<h2>Login</h2>
		{% csrf_token %}
		{% for field in loginForm %}
			<div class="my-2">
				<label class="text-xl block mb-3" for="{{ field.name }}">{{ field.label }}</label>
				{{ field }}
			</div>
		{% endfor %}
		<input type="submit" value="Login"
			   class="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
	</form>
{% endblock content %}

ai_apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>My Ai_Apps--{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'tailwind_app/css/tailwind.css' %}">
</head>
<body>
<div class="flex mx-5 my-10">
	<a class="cus-navbtn" href="{% url 'translator' %}">翻译助手</a>
	<a class="cus-navbtn" href="{% url 'email_writer' %}">邮件助手</a>
</div>

{% block content %}
{% endblock content%}





</body>
</html>

ai_apps/templates/base_for_ai_apps.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>My Ai_Apps--{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'tailwind_app/css/tailwind.css' %}">
	<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
	<!-- 这个可以使得网页根据屏幕大小做适配 -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/csrf.js' %}"></script>
	{% block headers %}
	{% endblock headers %}
</head>
<body>
<div class="flex mx-5 my-10">
	<a class="cus-navbtn" href="{% url 'translator' %}">翻译助手</a>
	<a class="cus-navbtn" href="{% url 'email_writer' %}">邮件助手</a>
	<a class="cus-navbtn" href="{% url 'csa' %}">客服助手</a>
	<a class="cus-navbtn" href="{% url 'chatbot' %}">聊天助手</a>
</div>

{% block content %}
{% endblock content %}



</body>
</html>

ai_apps/templates/customer_service_assistant.html
{% extends 'base_for_ai_apps.html' %}
{% load static %}

{% block title %}
	邮件助手
{% endblock title %}

{% block content %}
	<div class="relative mt-10">
		<form class="block w-3/4 mx-auto" novalidate>
			{% csrf_token %}
			{% for field in CustomerServiceAssistantForm %}
				<div class="my-2">
					<label class="text-xl block mb-3" for="{{ field.name }}">{{ field.label }}</label>
					{{ field }}
					{{ endfor }}
				</div>
			{% endfor %}

			<button id="stopbtn"
					class="my-5 bg-blue-500 hover:bg-blue-700 text-white text-xl font-bold py-3 px-8 rounded"
					type="button">停止
			</button>
			<button id="generateReplyBtn"
					class="w-full my-5 bg-blue-500 hover:bg-blue-700 text-white text-xl font-bold py-3 rounded"
					type="button">
				生成邮件
			</button>
		</form>
	</div>

	<script>
        $(function () {
            // 点击翻译事件
            $('#generateReplyBtn').click(function () {
                streamEvent();
            });
            $('#id_customer_message, #id_my_extra_requirement, #id_include_info').keydown(function (event) {
                handleShiftEnter(event)
            });
            // 点击停止事件
            $('#stopbtn').click(function () {
                stopGernerateEvent();
            });

        });

        let lastCustomerMessage = ''
        let lastMyExtraRequirement = ''
        let lastIncludeInfo = ''

        function streamEvent() {
            customer_message = $('#id_customer_message').val()
            my_extra_requirement = $('#id_my_extra_requirement').val();
            include_info = $('#id_include_info').val();
            // 如果内容相同，不连接后端，省钱
            if (customer_message == lastCustomerMessage && my_extra_requirement == lastMyExtraRequirement && include_info == lastIncludeInfo) {
                alert('请勿重复提交')
                return
            } else {
                // 如果内容不同，连接后端，并且更新lastReceivedEmail
                // 取到
                lastCustomerMessage = customer_message;
                lastIncludeInfo = include_info;
                lastMyExtraRequirement = my_extra_requirement;

            }
            // 判断text有没有内容
            if (!customer_message || !my_extra_requirement || !include_info) {
                // 内容为空不连接后端，省钱
                alert('请输入要回复的邮件的内容')
            } else {
                // 内容不为空，连接后端
                stop = "false"  // 设置get请求的stop参数，在后端判断是否停止
				// 清空id=id_my_reply的textarea框的值
                $('#id_my_reply').val('')
                const eventSource = new EventSource(`{% url 'pack_reply_stream' %}?stop=${stop}&customer_message=${customer_message}&my_extra_requirement=${my_extra_requirement}&include_info=${include_info}`);
                eventSource.addEventListener('message', function (e) {
                    const data = e.data;
                    if (data == '') {
                        // 如果data为空，说明后端已经停止了，关闭连接
                        eventSource.close()
                        console.log("由于后端停止，关闭sse连接")
                    } else {
                        console.log("data:", data, typeof (data)) // 输出data,是string类型
                        // 解析JSON格式的数据，将json字符串转换成json对象
                        var pasedData = JSON.parse(data);
                        var paredContent = pasedData.content
                        // 获取id=id_translation的textarea框
                        var textarea = document.getElementById('id_my_reply');
                        textarea.value += paredContent;
                    }

                });
                // 处理连接断开的情况
                eventSource.addEventListener('error', function () {
                    console.error('连接已断开', "error");
                    // 如果需要，可以尝试重新连接
                });
            }
        }

        function handleShiftEnter(event) {
            if (event.shiftKey && event.keyCode == 13) {
                // 阻止默认行为（例如，不发送表单）
                event.preventDefault();
                // 在光标位置插入换行符
                var cursorPos = event.target.selectionStart;
                var textBefore = event.target.value.substring(0, cursorPos);
                var textAfter = event.target.value.substring(cursorPos, event.target.value.length);
                event.target.value = textBefore + "\n" + textAfter;
            }
            if (event.keyCode == 13) {
                // 运行streamEvent函数
                event.preventDefault()
                // 每次按下回车键，清空id=id_translation的textarea框的值
                streamEvent()  // 直接调用全局的 streamEvent 函数
            }
        }

        function stopGernerateEvent() {
            stop = "true"
            const eventSource = new EventSource(`{% url 'pack_reply_stream' %}?text=${text}&stop=${stop}`);
            eventSource.close()

        }


	</script>
{% endblock %}

ai_apps/templates/email_writer.html
{% extends 'base_for_ai_apps.html' %}
{% load static %}

{% block title %}
	邮件助手
{% endblock title %}

{% block content %}
	<div class="relative mt-10">
		<form class="block w-3/4 mx-auto" novalidate>
			{% csrf_token %}
			{% for field in emailWriterForm %}
				<div class="my-2">
					<label class="text-xl block mb-3" for="{{ field.name }}">{{ field.label }}</label>
					{{ field }}
					{{ endfor }}
				</div>
			{% endfor %}

			<button id="stopbtn"
					class="my-5 bg-blue-500 hover:bg-blue-700 text-white text-xl font-bold py-3 px-8 rounded"
					type="button">停止
			</button>
			<button id="generateEmailBtn"
					class="w-full my-5 bg-blue-500 hover:bg-blue-700 text-white text-xl font-bold py-3 rounded"
					type="button">
				生成邮件
			</button>
		</form>
	</div>



	<script>
        $(function () {
            // 点击运行streamEvent函数
            $('#generateEmailBtn').click(function () {
                streamEvent();
            });
            // 按下Enter键运行streamEvent函数
            $('#id_received_email, #id_my_extra_requirement, #id_include_info').keydown(function (event) {
                handleShiftEnter(event);
            });
            // 点击停止事件
            $('#stopbtn').click(function () {
                stopGernerateEvent();
            });

        });

        let lastReceivedEmail = ''
        let lastMyExtraRequirement = ''
        let lastIncludeInfo = ''

        function streamEvent() {
            received_email = $('#id_received_email').val()
            my_extra_requirement = $('#id_my_extra_requirement').val();
            include_info = $('#id_include_info').val();
            // 如果内容相同，不连接后端，省钱
            if (received_email == lastReceivedEmail && my_extra_requirement == lastMyExtraRequirement && include_info == lastIncludeInfo) {
                alert('请勿重复提交')
                return
            } else {
                // 如果内容不同，连接后端，并且更新lastReceivedEmail
                // 取到
                lastReceivedEmail = received_email;
                lastIncludeInfo = include_info;
                lastMyExtraRequirement = my_extra_requirement;

            }
            // 判断text有没有内容
            if (!received_email || !my_extra_requirement || !include_info) {
                // 内容为空不连接后端，省钱
                alert('请输入要回复的邮件的内容')
            } else {
                // 内容不为空，连接后端
                stop = "false"  // 设置get请求的stop参数，在后端判断是否停止
                $('#id_my_response_email').val('')
                const eventSource = new EventSource(`{% url 'pack_email_stream' %}?stop=${stop}&received_email=${received_email}&my_extra_requirement=${my_extra_requirement}&include_info=${include_info}`);
                eventSource.addEventListener('message', function (e) {
                    const data = e.data;
                    if (data == '') {
                        // 如果data为空，说明后端已经停止了，关闭连接
                        eventSource.close()
                        console.log("由于后端停止，关闭sse连接")
                    } else {
                        console.log("data:", data, typeof (data)) // 输出data,是string类型
                        // 解析JSON格式的数据，将json字符串转换成json对象
                        var pasedData = JSON.parse(data);
                        var paredContent = pasedData.content
                        // 获取id=id_translation的textarea框
                        var textarea = document.getElementById('id_my_response_email');
                        textarea.value += paredContent;
                    }

                });
                // 处理连接断开的情况
                eventSource.addEventListener('error', function () {
                    console.error('连接已断开', "error");
                    // 如果需要，可以尝试重新连接
                });
            }
        }

        function handleShiftEnter(event) {
            if (event.shiftKey && event.keyCode == 13) {
                // 阻止默认行为（例如，不发送表单）
                event.preventDefault();
                // 在光标位置插入换行符
                var cursorPos = event.target.selectionStart;
                var textBefore = event.target.value.substring(0, cursorPos);
                var textAfter = event.target.value.substring(cursorPos, event.target.value.length);
                event.target.value = textBefore + "\n" + textAfter;
            }
            if (event.keyCode == 13) {
                // 运行streamEvent函数
                event.preventDefault()
                // 每次按下回车键，清空id=id_translation的textarea框的值
                streamEvent()  // 直接调用全局的 streamEvent 函数
            }
        }

        function stopGernerateEvent() {
            stop = "true"
            const eventSource = new EventSource(`{% url 'pack_email_stream' %}?text=${text}&stop=${stop}`);
            eventSource.close()

        }


	</script>
{% endblock %}

ai_apps/templates/index_for_ai_apps.html
{% extends "base_for_ai_apps.html" %}
{% load static %}

{% block title %}
	主页
{% endblock title %}




{% block content %}
	<div>
		ai_apps 的 index
	</div>
{% endblock content %}